feat: add "About the Boring Education" section with logo and project link
The-Boring-Education/TBE-Web pull request #138
Opened 2024-12-18 08:20 UTC by POBOROJO

This pull request includes changes to the `src/pages/webinar/[webinarSlug]/index.tsx` file to enhance the content and functionality of the Webinar page. The most important changes include adding new imports for components and constants, and introducing a new section about "The Boring Education" with relevant content and a call-to-action button.

Enhancements to the Webinar page:

* `src/pages/webinar/[webinarSlug]/index.tsx`: Added imports for `imageMeta` from `@/constant/global` and `LinkButton` from `@/components/common/Buttons/LinkButton`. ([src/pages/webinar/[webinarSlug]/index.tsxR16-R17](diffhunk://#diff-7968a24aa67c0c9f80428ac23643a9cbcd61936558128d0294e2d6f660633255R16-R17))
* `src/pages/webinar/[webinarSlug]/index.tsx`: Introduced a new section with a heading "About the Boring Education", an image, a descriptive text, and a `LinkButton` that directs users to explore free projects. ([src/pages/webinar/[webinarSlug]/index.tsxR250-R287](diffhunk://#diff-7968a24aa67c0c9f80428ac23643a9cbcd61936558128d0294e2d6f660633255R250-R287))

2024-12-18 08:46 UTC, imsks requested changes

2024-12-18 08:46 UTC, imsks commented on src/pages/webinar/[webinarSlug]/index.tsx
> +import LinkButton from '@/components/common/Buttons/LinkButton';
always use Root address like @/constant or @/components not @/components/common/Buttons/LinkButton

2024-12-18 09:07 UTC, POBOROJO commented
Done

2024-12-19 05:48 UTC, imsks requested changes

2024-12-19 05:48 UTC, imsks commented on src/constant/routes.ts
>      project: (project: string) => `/projects/${project}`,
We need this route. Why did you delete this

2024-12-19 05:48 UTC, imsks commented on src/pages/webinar/[webinarSlug]/index.tsx
> +      console.log('Certificate generation response:', response);
Remove logs after development

2024-12-19 05:48 UTC, imsks commented on src/pages/webinar/[webinarSlug]/index.tsx
> +      console.log('Generating Certificate for:', user?.email);
Here also

2024-12-19 05:48 UTC, imsks commented on src/pages/webinar/[webinarSlug]/index.tsx
> +      // if (!response?.status) {
Remove commented code

2024-12-19 17:06 UTC, imsks approved these changes

2024-12-19 17:06 UTC, merged