add nterview Prep in Navbar
The-Boring-Education/TBE-Web pull request #64
Opened 2024-10-24 10:31 UTC by harshad00

#59

2024-10-24 10:46 UTC, imsks requested changes

2024-10-24 10:46 UTC, imsks commented on src/constant/global.ts
> +    slug: '/interviewPrep',
slug should be "/interview-prep". Follow existing code stye

2024-10-24 10:46 UTC, imsks commented on src/interfaces/global.ts
> +  | 'InterviewPrep'
Interview Prep not InterviewPrep

2024-10-24 18:12 UTC, harshad00 commented
maybe now we will not have issues and have any problems tall me.

2024-10-25 11:35 UTC, imsks commented
We've fixed and merged this already. Please pick another task.

2024-10-25 11:35 UTC, closed without merging