Add Shiksha  my-courses
The-Boring-Education/TBE-Web pull request #71
Opened 2024-10-28 03:51 UTC by harshad00

`/shiksha/my-courses`
![Screenshot 2024-10-28 092040](https://github.com/user-attachments/assets/7969f006-9ae4-491e-8247-4e8891a2a785)

2024-10-28 17:21 UTC, imsks requested changes

2024-10-28 17:21 UTC, imsks commented on src/constant/global.ts
this change is not Needed for My Course. Always work on 1 task for 1 PR.

2024-10-28 17:21 UTC, imsks commented on src/constant/pages/index.ts
this change is not Needed for My Course. Always work on 1 task for 1 PR.

2024-10-28 17:21 UTC, imsks commented on src/constant/routes.ts
> +  shikshaMycu: '/shiksha/courses',
this not needed. Explore page already exists.

2024-10-28 17:21 UTC, imsks commented on src/constant/routes.ts
> +  shikshaCourses: '/shiksha/my-courses',
name it like shikshaUserCourses

2024-10-28 17:21 UTC, imsks commented on src/constant/routes.ts
> +      shiksha_courses: 'shiksha_courses',
Not sure if needed. Even if needed then follow the same code style. write like shikshaCourses.

2024-10-28 17:21 UTC, imsks commented on src/interfaces/global.ts
> +  | 'Interview Prep'
this change is not Needed for My Course. Always work on 1 task for 1 PR.

2024-10-28 17:21 UTC, imsks commented on src/pages/interview-prep/index.tsx
> +
Remove empty lines.

2024-10-28 17:21 UTC, imsks commented on src/pages/shiksha/my-courses/index.tsx
This is wrong implementation. You'll need to call Get User Courses API and show Courses.

2024-10-28 17:22 UTC, imsks commented
@harshad00 Please work on every comment and fix them. Your implementation is wrong. check how we're fetching All Courses. All you've to do is just Implement it for One User.

2024-10-28 17:23 UTC, imsks commented
@harshad00 Always resolve the comments like 
![image](https://github.com/user-attachments/assets/aab99ad7-0eaf-4089-849f-a186dc0f9a58)

2024-10-29 18:07 UTC, harshad00 commented
I mistakenly made this branch from  `TWE_Web#59` that because it had unnecessary changes.  can I Close this PR and make new  branch from `production`  and male new PR.

2024-10-29 18:47 UTC, imsks commented
Pick another task. This one is picked internally

On Tue, 29 Oct 2024 at 11:37 PM, Harshad Prajapati ***@***.***>
wrote:

> I mistakenly made this branch from TWE_Web#59 that because it had
> unnecessary changes. can I Close this PR and make new branch from
> production and male new PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/The-Boring-Education/TBE-Web/pull/71#issuecomment-2444998195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG6LTCKEHOWDZX42YNEUNU3Z57FFVAVCNFSM6AAAAABQWQSFBOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBUHE4TQMJZGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-01 05:06 UTC, closed without merging