created an API endpoint to get all the questions of a specific user
The-Boring-Education/TBE-Web pull request #86
Opened 2024-10-30 09:18 UTC by BunnyBharath91

Created a new API endpoint to retrieve all questions associated with a specific user based on their userId.

2024-10-30 09:26 UTC, imsks requested changes

2024-10-30 09:26 UTC, imsks commented on src/pages/api/v1/user/interview-prep/questions.ts
instead of creating a new file you can put under src/pages/api/v1/user/interview-prep/sheet.ts because you're technically fetching all Questions for a Sheet only but for User.

2024-10-30 09:26 UTC, imsks commented on src/pages/api/v1/user/interview-prep/questions.ts
Plus src/pages/api/v1/user/interview-prep/sheet.ts has no GET Method so no issues will happen

2024-10-30 09:37 UTC, BunnyBharath91 commented
included questions.ts file into sheet.ts file.

2024-10-31 05:21 UTC, imsks approved these changes

2024-10-31 05:21 UTC, merged