Add User Project Model
The-Boring-Education/TBE-Web pull request #89
Opened 2024-11-01 05:05 UTC by harshad00

added  User Project Mode

2024-11-03 17:50 UTC, harshad00 commented
Hello, By mistake I wrote User Progress Model as User Project Model I am solving the problem can you check and give me feedback

2024-11-04 17:31 UTC, imsks requested changes

2024-11-04 17:31 UTC, imsks commented on src/constant/database.ts
> +  PROGRESS_TASK: 'ProgressTask',
When naming a variable, make it descriptive like USER_PROJECT_PROGRESS

2024-11-04 17:31 UTC, imsks commented on src/interfaces/database.ts
> +export interface UserProgressModel {
While UserProgressModel is fine but we've different products which need User Progress Feature so we can't use generic UserProgressModel name we need to Identify Product name also like UserProjectProgressModel

2024-11-04 18:17 UTC, harshad00 commented on src/constant/database.ts
> +  PROGRESS_TASK: 'ProgressTask',
changed name

2024-11-13 07:22 UTC, imsks commented
Implemented.

2024-11-13 07:22 UTC, closed without merging